startDelaySeconds: 0
hostPort: localhost:7778
username:
password:
ssl: false
lowercaseOutputName: true
rules:

- pattern : java.lang<type=GarbageCollector, name=(G1 Young Generation|G1 Old Generation)><LastGcInfo>(duration|GcThreadCount)
  name: gc_lastgc
  labels:
    space: "$1"
    type: "$2"
